before:
  hooks:
builds:
  - id: l2geth-darwin
    dir: l2geth/cmd/geth
    binary: l2geth
    env: *cgo_darwin
    goos:
      - darwin
    goarch:
      - arm64
      - amd64
  - id: l2geth-linux-amd64
    dir: l2geth/cmd/geth
    binary: l2geth
    env: *cgo_linux_amd64
    goos:
      - linux
    goarch:
      - amd64
  - id: l2geth-linux-arm64
    dir: l2geth/cmd/geth
    binary: l2geth
    env: *cgo_linux_arm64
    goos:
      - linux
    goarch:
      - arm64
archives:
#  - format: binary
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
