before:
  hooks:
builds:
  - id: l2geth-darwin
    dir: l2geth/cmd/geth
    binary: l2geth
    env:
      - GO111MODULE=on
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
    goos:
      - darwin
    goarch:
      - arm64
      - amd64
  - id: l2geth-linux-amd64
    dir: l2geth/cmd/geth
    binary: l2geth
    env:
      - GO111MODULE=on
      - CGO_ENABLED=1
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
    goos:
      - linux
    goarch:
      - amd64
  - id: l2geth-linux-arm64
    dir: l2geth/cmd/geth
    binary: l2geth
    env:
      - GO111MODULE=on
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    goos:
      - linux
    goarch:
      - arm64
archives:
#  - format: binary
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
