
networks:
  mantle:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1

services:
  scheduler:
    build:
      context: ..
      dockerfile: ./l2geth/Dockerfile.local
    image: mantlenetworkio/l2geth:${DOCKER_TAG_L2GETH:-latest}
    # override with the geth script and the env vars required for it
    entrypoint: sh ./geth.sh
    env_file:
      - ./envs/geth.env
    container_name: bitscheduler
    volumes:
      - ~/data/mantle_sequencer/scheduler:/root/.ethereum/geth/
    environment:
      ETH1_HTTP: http://10.0.0.2:8545
      SEQUENCER_L1_RPC: http://10.0.0.2:8545
      ROLLUP_TIMESTAMP_REFRESH: 5s
      ROLLUP_STATE_DUMP_PATH: http://10.0.0.3:8081/state-dump.latest.json
      # connecting to the DTL
      ROLLUP_CLIENT_HTTP: http://dtl:7878
      ETH1_CTC_DEPLOYMENT_HEIGHT: 8
      RETRIES: 60
      # no need to keep this secret, only used internally to sign blocks
      BLOCK_SIGNER_KEY: 'ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80'
      BLOCK_SIGNER_ADDRESS: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'
      BLOCK_SCHEDULER_ADDRESS: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'
      SEQUENCER_CONTRACT_ADDRESS: '0xBe0F340075060F856612d91e17cAe599dE92C745'
      ROLLUP_ENFORCE_FEES: ${ROLLUP_ENFORCE_FEES:-false}
      ROLLUP_FEE_THRESHOLD_DOWN: 0.9
      ROLLUP_FEE_THRESHOLD_UP: 1.1
      NODEKEY_HEX: 8ea7ea025ae02ff659294f741ce571b28606858dd80987b42f91b9f7b1bd7623
      GASPRICE: 0
      VERBOSITY: 3
      NAT: 'extip:172.17.0.1'
      IS_SCHEDULER: 'true'
    ports:
      - ${L2GETH_HTTP_PORT:-8545}:8545
      - ${L2GETH_WS_PORT:-8546}:8546
      - ${L2GETH_P2P_PORT:-30303}:30303
    networks:
      mantle:
        ipv4_address: 10.0.0.7

  sequencer1:
    depends_on:
      - scheduler
    deploy:
      replicas: 1
    build:
      context: ..
      dockerfile: ./l2geth/Dockerfile.local
    image: mantlenetworkio/l2geth:${DOCKER_TAG_L2GETH:-latest}
    entrypoint: sh ./geth.sh
    container_name: bitsequencer1
    env_file:
      - ./envs/geth.env
    volumes:
      - ./chaindata/sequencer1:/root/config
      - ~/data/mantle_sequencer/features/sequencer1:/root/.ethereum/geth/
    environment:
      ETH1_HTTP: http://10.0.0.2:8545
      SEQUENCER_L1_RPC: http://10.0.0.2:8545
      ROLLUP_TIMESTAMP_REFRESH: 5s
      ROLLUP_STATE_DUMP_PATH: http://10.0.0.3:8081/state-dump.latest.json
      # connecting to the DTL
      ROLLUP_CLIENT_HTTP: http://dtl:7878
      ETH1_CTC_DEPLOYMENT_HEIGHT: 8
      RETRIES: 60
      # no need to keep this secret, only used internally to sign blocks
      BLOCK_SIGNER_KEY: '5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a'
      BLOCK_SIGNER_ADDRESS: '0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC'
      BLOCK_SCHEDULER_ADDRESS: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'
      SEQUENCER_CONTRACT_ADDRESS: '0xBe0F340075060F856612d91e17cAe599dE92C745'
      ROLLUP_ENFORCE_FEES: ${ROLLUP_ENFORCE_FEES:-false}
      ROLLUP_FEE_THRESHOLD_DOWN: 0.9
      ROLLUP_FEE_THRESHOLD_UP: 1.1
      IS_SEQUENCER: 'true'
      NODEKEY_HEX: 0b230e4787022b0dead74c0f16eddc966075109c8945e7c23822bf05ef2459f6
      P2P_PORT: 30313
      NAT: 'extip:172.17.0.1'
      CONFIG_PATH: '/root/config/config.toml'
      SCHEDULER_P2P_ENODE: 'enode://09998ab210032351a2bea94fbb8c867cfc95553019d3cecfe0d3f3aef78b24290e624b07a99fdaa3c2fb9015d193303179b396e3520284d249ef9a233a5f5e62@172.17.0.1:30303?discport=0'
    ports:
      - ${L2GETH_HTTP_PORT:-7545}:8545
      - ${L2GETH_WS_PORT:-7546}:8546
      - ${L2GETH_P2P_PORT:-30313}:30313
    networks:
      mantle: {}

  sequencer2:
    depends_on:
      - scheduler
    deploy:
      replicas: 1
    build:
      context: ..
      dockerfile: ./l2geth/Dockerfile.local
    image: mantlenetworkio/l2geth:${DOCKER_TAG_L2GETH:-latest}
    entrypoint: sh ./geth.sh
    container_name: bitsequencer2
    env_file:
      - ./envs/geth.env
    volumes:
      - ./chaindata/sequencer2:/root/config
      - ~/data/mantle_sequencer/features/sequencer2:/root/.ethereum/geth/
    environment:
      ETH1_HTTP: http://10.0.0.2:8545
      SEQUENCER_L1_RPC: http://10.0.0.2:8545
      ROLLUP_TIMESTAMP_REFRESH: 5s
      ROLLUP_STATE_DUMP_PATH: http://10.0.0.3:8081/state-dump.latest.json
      # connecting to the DTL
      ROLLUP_CLIENT_HTTP: http://dtl:7878
      ETH1_CTC_DEPLOYMENT_HEIGHT: 8
      RETRIES: 60
      # no need to keep this secret, only used internally to sign blocks
      BLOCK_SIGNER_KEY: '59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d'
      BLOCK_SIGNER_ADDRESS: '0x70997970C51812dc3A010C7d01b50e0d17dc79C8'
      BLOCK_SCHEDULER_ADDRESS: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'
      SEQUENCER_CONTRACT_ADDRESS: '0xBe0F340075060F856612d91e17cAe599dE92C745'
      ROLLUP_ENFORCE_FEES: ${ROLLUP_ENFORCE_FEES:-false}
      ROLLUP_FEE_THRESHOLD_DOWN: 0.9
      ROLLUP_FEE_THRESHOLD_UP: 1.1
      IS_SEQUENCER: 'true'
      NODEKEY_HEX: b10769555457563821897073f910c3e47ccd33d030ee6cd7e9a19109e5f12a91
      P2P_PORT: 30323
      CONFIG_PATH: '/root/config/config.toml'
      SCHEDULER_P2P_ENODE: 'enode://09998ab210032351a2bea94fbb8c867cfc95553019d3cecfe0d3f3aef78b24290e624b07a99fdaa3c2fb9015d193303179b396e3520284d249ef9a233a5f5e62@172.17.0.1:30303?discport=0'
      NAT: 'extip:172.17.0.1'
    ports:
      - ${L2GETH_HTTP_PORT:-7543}:8545
      - ${L2GETH_WS_PORT:-7544}:8546
      - ${L2GETH_P2P_PORT:-30323}:30323
    networks:
      mantle: {}

  replica1:
    depends_on:
      - scheduler
    # deploy:
    #   replicas: 1
    build:
      context: ..
      dockerfile: ./l2geth/Dockerfile.local
    image: mantlenetworkio/l2geth:${DOCKER_TAG_L2GETH:-latest}
    entrypoint: sh ./geth.sh
    container_name: bitreplica1
    volumes:
      - ~/data/mantle_sequencer/replica1:/root/.ethereum/geth/
    env_file:
      - ./envs/geth.env
    environment:
      ETH1_HTTP: http://10.0.0.2:8545
      SEQUENCER_L1_RPC: http://10.0.0.2:8545
      SEQUENCER_CLIENT_HTTP: http://scheduler:8545
      ROLLUP_STATE_DUMP_PATH: http://10.0.0.3:8081/state-dump.latest.json
      ROLLUP_CLIENT_HTTP: http://dtl:7878
      BLOCK_SIGNER_KEY: '6395a7c842a08515961888d21d72f409b61fbce96af1e520384e375f301a8297'
      BLOCK_SIGNER_ADDRESS: '0xCd0B4E309FB855d644bA64E5fb3dC3DD08f13917'
      BLOCK_SCHEDULER_ADDRESS: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'
      SEQUENCER_CONTRACT_ADDRESS: '0xBe0F340075060F856612d91e17cAe599dE92C745'
      ROLLUP_BACKEND: 'l2'
      ROLLUP_VERIFIER_ENABLE: 'false'
      ETH1_CTC_DEPLOYMENT_HEIGHT: 8
      RETRIES: 60
      IS_SEQUENCER: 'false'
    ports:
      - ${REPLICA_HTTP_PORT:-8549}:8545
      - ${REPLICA_WS_PORT:-8550}:8546
    networks:
      mantle: {}

  replica2:
    depends_on:
      - scheduler
    # deploy:
    #   replicas: 1
    build:
      context: ..
      dockerfile: ./l2geth/Dockerfile.local
    image: mantlenetworkio/l2geth:${DOCKER_TAG_L2GETH:-latest}
    entrypoint: sh ./geth.sh
    container_name: bitreplica2
    volumes:
      - ~/data/mantle_sequencer/features/replica2:/root/.ethereum/geth/
    env_file:
      - ./envs/geth.env
    environment:
      ETH1_HTTP: http://10.0.0.2:8545
      SEQUENCER_L1_RPC: http://10.0.0.2:8545
      SEQUENCER_CLIENT_HTTP: http://scheduler:8545
      ROLLUP_STATE_DUMP_PATH: http://10.0.0.3:8081/state-dump.latest.json
      ROLLUP_CLIENT_HTTP: http://dtl:7878
      BLOCK_SIGNER_KEY: '6395a7c842a08515961888d21d72f409b61fbce96af1e520384e375f301a8297'
      BLOCK_SIGNER_ADDRESS: '0xCd0B4E309FB855d644bA64E5fb3dC3DD08f13917'
      BLOCK_SCHEDULER_ADDRESS: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'
      SEQUENCER_CONTRACT_ADDRESS: '0xBe0F340075060F856612d91e17cAe599dE92C745'
      ROLLUP_BACKEND: 'l2'
      ROLLUP_VERIFIER_ENABLE: 'false'
      ETH1_CTC_DEPLOYMENT_HEIGHT: 8
      RETRIES: 60
      IS_SEQUENCER: 'false'
    ports:
      - ${REPLICA_HTTP_PORT:-8551}:8545
      - ${REPLICA_WS_PORT:-8552}:8546
    networks:
      mantle: {}

  verifier:
    depends_on:
      - scheduler
    # deploy:
    #   replicas: 1
    build:
      context: ..
      dockerfile: ./l2geth/Dockerfile.local
    image: mantlenetworkio/l2geth:${DOCKER_TAG_L2GETH:-latest}
    entrypoint: sh ./geth.sh
    container_name: bitverifier
    env_file:
      - ./envs/geth.env
    volumes:
      - ~/data/mantle_sequencer/verifier:/root/.ethereum/geth/
    environment:
      ETH1_HTTP: http://10.0.0.2:8545
      SEQUENCER_L1_RPC: http://10.0.0.2:8545
      SEQUENCER_CLIENT_HTTP: http://scheduler:8545
      ROLLUP_STATE_DUMP_PATH: http://10.0.0.3:8081/state-dump.latest.json
      ROLLUP_CLIENT_HTTP: http://dtl:7878
      BLOCK_SIGNER_KEY: '6395a7c842a08515961888d21d72f409b61fbce96af1e520384e375f301a8297'
      BLOCK_SIGNER_ADDRESS: '0xCd0B4E309FB855d644bA64E5fb3dC3DD08f13917'
      BLOCK_SCHEDULER_ADDRESS: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'
      SEQUENCER_CONTRACT_ADDRESS: '0xBe0F340075060F856612d91e17cAe599dE92C745'
      ROLLUP_BACKEND: 'l1'
      ETH1_CTC_DEPLOYMENT_HEIGHT: 8
      RETRIES: 60
      ROLLUP_VERIFIER_ENABLE: 'true'
      IS_SEQUENCER: 'false'
    ports:
      - ${VERIFIER_HTTP_PORT:-8547}:8545
      - ${VERIFIER_WS_PORT:-8548}:8546
    networks:
      mantle: {}
