name: Mantle App Batch-submitter Image Building
on:
  pull_request:
    branches:
      - main
    paths:
      - 'batch-submitter/*'
      - 'bss-core/*'
      - 'l2geth/*'
    types:
      - closed

jobs:
  l2geth:
    name: Publish Batch-Submitter Version ${{ github.event.pull_request.number }}
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_SECRET }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Publish Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./batch-submitter/Dockerfile
          push: true
          tags: mantlenetworkio/batch-submitter:${{ github.event.pull_request.number }}