name: Mantle App GasOracle Image Building
on:
  pull_request:
    branches:
      - main
    paths:
      - 'gas-oracle/*'
    types:
      - closed

jobs:
  l2geth:
    name: Publish L2Geth Version ${{ github.event.pull_request.number }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_SECRET }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Push Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./gas-oracle/Dockerfile
          push: true
          tags: mantlenetworkio/gas-oracle:${{ github.event.pull_request.number }}